alphagov/pay-jenkins-library

vars/runEndToEnd.groovy

Only run zap tests on master

---

vars/dockerTag.groovy

PP-1866 Fix Docker tagging

---

README.md
vars/buildApp.groovy

- Updated buildApp to run separate build and test image on frontend and selfservice

PP-2497 Decrease node image size

---

vars/deployPaas.groovy

This will trigger the pass deploy pipeline, which is different to AWS apps deploy pipeline
with @georgeracu

PP-2614 add deployPaas job

---

vars/deploy.groovy
vars/deployEcs.groovy

deployECS library function to call the deploy-ecs-microservice Jenkins job.

ECS deploy task

---

vars/runProductsEndToEnd.groovy

They are not required. as per https://docs.google.com/document/d/1L5spo6vCbU9ThTblFpKDlqefYtHL3LqeCaC0xUKo3U0

PP-2855 switching off accept tests for products tests

---

vars/buildApp.groovy

Added `directdebit-frontend` to the Jenkins build

PP-2809 Added directdebit-frontend to the Jenkins build

---

vars/deployEcs.groovy

Products requires 2 new parameters, SMOKE_TAGS and PROMOTED_ENV.
Products run selenium smoke tests
solo @belindac

PP-3253 ECSify Products in Test

---

vars/deployEcs.groovy

##WHAT 
Defaults promoted environment to 'true' which affects the domain choice in deployments

Default promoted environment to 'true'

---

vars/MetricsUtils.groovy
vars/buildAppWithMetrics.groovy
vars/dockerTagWithMetrics.groovy
vars/mavenBuildWithMetrics.groovy

environment
Add metrics for maven build, unit tests and docker build
solo @belindac

PP-3381 Instrument all stages of a master build and deployment to Test

---

README.md

environment
Update documentation
solo @belindac

PP--3381 Instrument all stages of a master build and deployment to Test

---

vars/tagDeployment.groovy
vars/triggerGraphiteDeployEvent.groovy

Corrected build job name - should have been actual job name, not the
groovy script file name
solo @belindac

PP-3527 Separate deployment, smoke test and tagging jobs

---

vars/triggerGraphiteDeployEvent.groovy

Don't need to pass in user (and we were doing so incorrectly)

PP-3527 Fix trigger deploy notification

---

vars/runPactTest.groovy

The provider sha needs to be got from within the ${providerProjectName}
directory.
@oswaldquek

PP-3616: Get correct provider sha

---

vars/runProviderContractTests.groovy

PP-3627: Script for running provider contract tests

---

vars/tagPact.groovy

Provider and Consumer services use tagPact to tag their pacts.
@oswaldquek

bau: Update parameter names

---

resources/cypress/cypress.yml

> Include _HOST alias expected by frontend

PP-4754: Include _HOST alias expected by frontend

---

vars/gitClone.groovy
vars/runPactProviderTests.groovy

This reverts commit adae4429616dcd145a44a9b33fef2ce1b6a8df29.
Because it broke stuff

Revert "Make contract tests more robust"

---

vars/runAppE2E.groovy
vars/runCardPaymentsE2E.groovy
vars/runDirectDebitE2E.groovy
vars/runProductsE2E.groovy
vars/runZap.groovy

Make use of the changes introduced in https://github.com/alphagov/pay-chef/pull/899

Use the single variant of the end to end job

---

vars/runCardSmokeTest.groovy
vars/runDirectDebitSmokeTest.groovy
vars/runProductsSmokeTest.groovy
vars/runSmokeTest.groovy

SMOKE_TAGS is deprecated in favour of SMOKE_TEST now.

Use the new-style smoke test job parameters

---

resources/cypress/cypress.yml

Ledger is now tested with self service Cypress tests. Point LEDGER_URL
to stub server for app under test.

PP-5603 Add LEDGER_URL to Cypress Jenkins yml

---

resources/cypress/cypress.yml

Reverts alphagov/pay-jenkins-library#130

Revert "PP-6008 Use new mountebank docker image"

---

resources/cypress/cypress.yml
vars/buildAppWithMetrics.groovy
vars/buildMultistageAppWithMetrics.groovy

Add new build task for multistage node builds.
Initially for use by frontend. See example of it working here
https://build.ci.pymnt.uk/job/pay-frontend/job/multistage/19/

PP-9153 Add multistage build task

---

vars/buildAppWithMetrics.groovy

Existing frontend master still needs to be built with existing buildWithAppMetrics

BAU Fix frontend build
