alphagov/pay-jenkins-library

- vars/buildApp.groovy
- vars/dockerTag.groovy
Removes Docker tagging code from the `buildApp` function and moves it into a separate `dockerTag` function.
The Jenkinsfile for each project will need to change to accommodate this. For example:
```
// … more stages …
stage('Docker Build') {
steps {
script {
buildApp{
app = "selfservice"
}
}
}
}
stage('Test') {
steps {
runEndToEnd("selfservice")
}
}
// Call the new function
stage('Docker Tag') {
steps {
script {
dockerTag{
app = "selfservice"
}
}
}
}
// … more stages …
```
> PP-1866 Separate out function for Docker tagging

- vars/runEndToEnd.groovy
The git branch was not being fetched correctly, so zap tests were not being run on master builds.
> fix git branch in runEndToEnd job

- vars/runProductsEndToEnd.groovy
This job triggers `run-end-to-end` job with `end2end-products` test profile. Which in turn will trigger only tests tagged for `products`. 
unlike other modules this job does not need to trigger ZAP tests on any test run. (see https://docs.google.com/document/d/1L5spo6vCbU9ThTblFpKDlqefYtHL3LqeCaC0xUKo3U0)
So always keeping to to `false`
> PP-2855 introduce ProductsEndToEnd pipeline job

- vars/deployEcs.groovy
We were passing through a parameter called `CONTAINER_VERSION`
when the job expects `MICROSERVICE_IMAGE_TAG` - see
https://github.com/alphagov/pay-chef/blob/master/cookbooks/pay-ci/templates/default/jenkins_jobs/deploy-ecs-microservice.groovy.erb#L18
> Fix container tag

- vars/runParameterisedEndToEnd.groovy
So that test profile can be used for various groups of test runs
> PP-2855 add includes excludes junit categories to the end2end job run

- vars/runParameterisedEndToEnd.groovy
As nulls are causing issues when gets passed in the to e2e bash script.
> PP-2923 add empty variables instead of null

- vars/deploy.groovy
So that, microservices can decide what bunch of smoke tests needs triggering after a deployment. This currently defaults to smoke test `v1` which is the current cucumber based smoke tests
Depends on pay-chef, pay-scripts PRs being merged
> PP-2996 allow deploy to specify smoke test category

- vars/deploy.groovy
aparantly, if jenkins job dsl setups default value as '' in stringParam, you cannot pass null in to it. So making `non produts` apps to pass empty instead of null.
> PP-2996 fix smoke tags to be non-null for default jobs

- vars/deploy.groovy
This variable `PROMOTED_ENV` must be set to true if you want to run smoke test with non-instance specific cnames (e.g. http://selfservice.test.pymnt.uk). This setting allows microservice to specify whether to use it or not depending on its desired smoke test version.
Note this only matters to test environment.
> PP-2996 Allowing pipeline jobs to specify to use PROMOTED_ENV

- vars/runParameterisedEndToEnd.groovy
- We are going to add a different run end to end job for directdebit (and
probably products).
We need to therefore be able to specify the job name in the runParamiterisedEndToEnd
script.
> PP-2939 Add job name to run parameterised end to end

- vars/buildApp.groovy
- Add disable docker cache optional config param in buildApp . So added as a config parameter for only when `buildApp` is executed as well as set as environment variable.
> PP-3378 Add disable docker cache optional config param in buildApp

- vars/buildApp.groovy
- Remove unused DISABLE_DOCKER_CACHE since if ever used docker build throws an error (flags interpreted as tag fails). So removed the environment variable in favour of config parameter.
- Fix order of parameter for docker build.
> PP-3378 Fix build flags position for docker build

- vars/buildAppWithMetrics.groovy
- vars/dockerTagWithMetrics.groovy
- vars/mavenBuildWithMetrics.groovy
environment
Removed import statement. Groovy scripts are evaluated into the same
package if in the same directory and are therefore available to each
other without any work
solo @belindac
> PP-3381 Instrument all stages of a master build and deployment to Test

- vars/postMetric.groovy
Move HG cred binding to where we need to use them, so we don't have to
push them in from top of Jenkinsfile/wherever.
> BAU refactor HG creds

- vars/runAccept.groovy
- vars/runE2E.groovy
- vars/runZap.groovy
- adds groovy tasks for ruby-based, separately run e2e, accept and zap tests
NOTE: This does not affect any existing pipelines at present as these are all new tasks currently unused by any project.
> PP-3436 Add separate definitions for separate e2e, accept and zap tests

- vars/runCardSmokeTest.groovy
- vars/runDirectDebitSmokeTest.groovy
- vars/runProductsSmokeTest.groovy
- vars/runSmokeTest.groovy
- vars/tagDeployment.groovy
- vars/triggerGraphiteDeployEvent.groovy
We want to be able to run different smoke tests per microservice but cannot currently as it is all bundled in one job. Created generic smoke test function with as much as possible defaulted
Added new jobs for tagging and deploy notification with as much defaulted as possible
solo @belindac
> PP-3527 Separate deployment, smoke test and tagging jobs [wip, no merge]

- vars/runCardSmokeTest.groovy
- vars/runDirectDebitSmokeTest.groovy
- vars/runProductsSmokeTest.groovy
- vars/runSmokeTest.groovy
There is now a base runSmokeTest library fn that calls
the `run-smoke-test` Jenkins job. That job uses the new
version of the smoke script (run-smokev2) if you pass it
`SMOKE_TAGS`. So all this works together, although a tad
complicated to trace through. Once we've transitioned over
we can delete all the old stuff and it will be clearer.
> PP-3527 Fix smoke test calls

- vars/deployEcs.groovy
All Jenkins files have been converted to use separated jobs so we can
now remove the arguments that were used for those jobs.
TODO: Remove all the tagging and smoke parameter values from all the
Jenkins files and then we can remove the method parameters
solo @belindac
> PP-3527 Separate deployment, smoke test and tagging jobs

- vars/runProductsSmokeTest.groovy
Temporarily disabling products smoke tests, to unblock the pipeline.
This has been tested using a branch when I fiddled around with the Jenkinsfile.
> PP-3596 temporarily disabling products smoke tests

- vars/buildAppWithMetrics.groovy
- vars/gitBranchName.groovy
- Add commit sha as PACT_CONSUMER_VERSION and PACT_CONSUMER_TAG as the first branch name related to this commit.
-  Since Jenkins checkout PR's using the commit sha and not a branch name, it needs to be extracted somehow, and the easiest way is finding the first branch that contains that commit, since PR's are build with new commits is unexpected that this will collide with others, an ouput example of a `git branch -a --contains {commit_sha} is:
`* (HEAD detached at 8b07ab7)
remote/origin/PP-3614-publish-pact-file-on-pr-build`
so it is extracted directly the second line of this output (3rd split by '/'), in case there is collision with other branches containing the same sha (it should not happen) it will still use the first branch with the given commit sha ignoring the others.
> PP-3614 publish pact files build

- vars/runAccept.groovy
See https://pay-team-manual.cloudapps.digital/arch/adr-002-deprecation-of-pay-accepttests/
> PP-3641 Stop running accept tests

- vars/runPactTest.groovy
The pact provider test needs the latest commit sha of the provider repo so the
pact broker can know which version of the consumer is verified against which
version of the provider.
@oswaldquek
> PP-3616: Publish pact verification result

- vars/checkPactCompatibility.groovy
If it is not deployable, the resultJson will look something like:
{"errors":["No pact or verification found for selfservice version adf5465625309137750c9118f5b5005d512f71324"]}. See https://build.ci.pymnt.uk/job/pay-selfservice/view/change-requests/job/PR-799/31/console as an example.
@oswaldquek
> PP-3625: Script to verify if a pacticipant is deployable

- vars/runDirectDebitSmokeTest.groovy
DD connector is broken, and DD team want to take some time to
diagnose the issue. While they do that we are disabling this smoke
test, so as not to block the pipeline. This will mean that
DD smoke tests won't be run post deploy to test, so some apps may
get to staging in a 'broken' state (though this is unlikely). If
they do, staging smoke tests will catch them.
> PP-3776 Temporarily disable direct debit smoke tests

- resources/cypress/cypress.yml
- vars/cypress.groovy
Adds Jenkins groovy scripts that run up a small Docker Compose environment for the purposes of Cypress browser testing. This consists of the application being tested (e.g. Self Service), the pact-stub container which is pre-loaded with pact files generated by that application running  unit tests, and finally a Cypress.io based image which has the browser testing files, along with any fixtures and dependencies.
This is implemented as a Docker Compose .yml file, as well as cypress.groovy, which is intended to be called as part of a Jenkins pipeline specific to the application being tested.
> PP-3813 run cypress tests in selfservice build

- vars/checkPactCompatibility.groovy
The latest=true query causes some builds to fail, even though the pact between
two services may be satisfied. We don't use the latest tag ever, only the
versions (git shas) so removing this.
@oswaldquek
> bau: Remove latest tag when querying to check for pact compatibility

- vars/runProviderContractTests.groovy
We have (or will be upgrading) java projects to use version 3.5.18 of the pact
jvm provider library, which disables publishing of verification result to the
pact broker by default. See https://github.com/DiUS/pact-jvm/issues/695. We
want to do this so results don't get accidentally published from development
machines.So we have to set the pact.verifier.publishResults to true here.
@oswaldquek
> bau: Specify a flag to publish verification results to the pact broker

- vars/gitBranchName.groovy
For some reason gitBranchName hasn't been working and getting spurious branch names.
`git rev-parse HEAD | git branch -a --contains` yields something like:
```
bau-dont-publish-verification-by-default
* bau-fix-gitBranchName
bau-remove-latest-tag
bau-update-parameter-names
master
```
we then grep the line containing `*` and use a `cut` to get the branch name.
@oswaldquek
> bau: fix gitBranchName function

- vars/gitBranchName.groovy
This reverts commit 8acad68b2c50a36b459d34ce3b67abeb7143eb9e.
This doesn't work in that it yields nothing in the pay-selfservice build :(
> Revert "bau: fix gitBranchName function"

- vars/runLocalPayScriptsUpdate.groovy
Pay-scripts master merges fail because the local repo is not up to date.
This allows us to call the update job before the master tests are run.
solo @belindac
> Script to call pay scripts update

- vars/runProviderContractTests.groovy
Provider tests are now hard coded to run pacts tagged with "master", "test",
"staging" and "production". See
https://github.com/alphagov/pay-connector/commit/667dea30defc7c3f9a5ac0bfa653c532ae206fc9
as an example.
@oswaldquek
> PP-4082: The PACT_CONSUMER_TAG property is no longer required

- resources/cypress/cypress.yml
- Seems that the `latest` version of `pact-stub-server` is failing with our
cypress tests for `Selfservice` which cause the stub server to freeze and stop
processing/accepting any new requests. This manifests itself as time-outs during
the cypress tests for `Selfservice` during the login page tests.
- Changing the `pact-stub-server` to reference the previous version
`v0.0.10'(which works locally on multiple machines) to unblock build of SelfService.
- We'll need to figure out why this is failing before this verison of `pact-stub-server`
is removed and then revert back to using `latest` tag.
- Note that previously passing cypress tests now fail with the latest
pact-stub-server and this doesn't appear to be something introduced by the
latest `Selfservice` changes; likely something that has …
> PP-4096 Using previous version of pack-stub-server

- vars/runProviderContractTests.groovy
This reverts commit 275cddf6def177dbe1eab4aff8ab1d6cdcd58cf3.
We actually still need the PACT_CONSUMER_TAG because provider PR builds need to
know the branch name via the PACT_CONSUMER_TAG.
> Revert "PP-4082: The PACT_CONSUMER_TAG property is no longer required"

- vars/getMasterHeadCommit.groovy
With the upgrade of the Github plugins, only the PR branch is fetched
and the build breaks trying to get the master head commit. Until the
job-dsl plugin supports setting ref specs we need to get the master
branch for this function
solo @belindac
> PP-4025 Master branch required for PRs

- vars/runProductsE2E.groovy
We were defaulting branch to `master` in products e2e script.
This meant it was impossible to build pay-scripts in certain
circumstances. Changing default to null to match other e2e scripts.
> PP-4213 Fix products e2e

- vars/runAppE2E.groovy
- vars/runCardPaymentsE2E.groovy
- vars/runDirectDebitE2E.groovy
- vars/runProductsE2E.groovy
Make the run*E2E pipeline steps use a common codebase rather than duplicating each other.
> BAU: Factor out duplicate code in run*E2E steps

- vars/runPactProviderTests.groovy
This resolves an issue where a new interaction is added in the consumer pact,
but does not require a change in the provider. When this happens, when the
provider contract test is run as part of the consumer build, the verification
result should be published. Otherwise, the consumer build will fail at the
deploy stage as no provider has verified the new interaction that was added in
the first place.
@oswaldquek
> bau: Publish verification when running provider test in a consumer build

- vars/runPactProviderTests.groovy
- vars/runProviderContractTests.groovy
The provider version set by the PROVIDER_SHA env var is actually a custom Pay
env var. The correct env var used by the pact libraries is
pact.provider.version.
@oswaldquek
> bau: Use correct env var to provide the provider version

- vars/runPactProviderTests.groovy
- vars/runProviderContractTests.groovy
This has been superseded by pact.verifier.publishResults env var.
@oswaldquek
> bau: PACT_PROVIDER_SHA is no longer used

- vars/cypress.groovy
We can simplify these shell snippets a bit and ensure it always exits with a
zero status code.
> Simplify cypress cleanUp()

- resources/cypress/cypress.yml
- vars/cypress.groovy
* Includes environment variables required new Cypress testing
infrastructure
* Replaces stub pact server with mountebank
Updates Cypress docker compose infrastructure required by https://github.com/alphagov/pay-selfservice/pull/1111. Shouldn't be merged until self service is ready to accept this PR.
> PP-4678: Update Docker compose definition

- vars/cypress.groovy
If containers fail to come up during Cypress tests, we don't know why because
the logs aren't captured.
Emit the logs
> Emit docker-compose logs after Cypress tests

- vars/gitTag.groovy
Our email domain is digital.cabinet-office.gov.uk, not
digital.cabinet-office.service.gov.uk
> Fix the email address used when creating git tags

- vars/gitClone.groovy
- vars/runPactProviderTests.groovy
Sometimes we attempt to clone a repo over the top of an existing directory
which fails.
Make this more robust by removing the directory if it already exists.
> Make contract tests more robust

- vars/tagDeployment.groovy
This parameter is now unused, so we don't need to pass it in any more.
See https://github.com/alphagov/pay-chef/pull/842/files#diff-9a65505c55558afaaaa36e8ca6dbcf2aR12
> Stop passing CALLER_BUILD_STATUS to run-tag-and-capture-notes-commit-based

- vars/runPactProviderTests.groovy
Remove the "-o" option from "set" in the shell script as this causes the error 
/var/lib/jenkins/contract-tests-wp__tmp/durable-184b4bc3/script.sh: 2: set: Illegal option -o pipefail
I don't know much about bash, so it may be that we need to do something else to fix this, but currently its breaking builds.
From looking at this https://sipb.mit.edu/doc/safe-shell/ are we using dash in the build rather than bash?
> Fix runPactProviderTests.groovy

- vars/checkPactCompatibility.groovy
- The curl command included pact versions for the consumer without a verification which were not the latest version with the tag.
- Rather than amending the request we make, use the pact-broker CLI as this is well documented and easier to understand.
> PP-5199 Use pact-broker CLI to get verification result

- vars/tagDeployment.groovy
Rather than call out to `run-tag-and-capture-notes-commit-based` as a separate
job, which clones a repo of scripts and then clones the repo of the application
we want to tag, we can just tag and push the repository we are within, inline
within the build job.
Convert our tagging script to groovy and inline it.
Disclaimer: I do not claim to be capable of producing idiomatic groovy code
This is in place of this job: https://github.com/alphagov/pay-chef/blob/master/cookbooks/pay-ci/templates/default/jenkins_jobs/tag-and-capture-notes-commit-based.groovy.erb
and this script: https://github.com/alphagov/pay-scripts/blob/master/deploy-pipeline/tagging/tag_and_capture_notes_commit_based.sh
The job and script are still used for tagging repositories following a database migration, which I think can …
> Tag repositories inline in their build jobs

- vars/tagDeployment.groovy
Reverts alphagov/pay-jenkins-library#115
From https://build.ci.pymnt.uk/job/pay-cardid/job/master/8/console:
```
Scripts not permitted to use method groovy.lang.GroovyObject invokeMethod java.lang.String java.lang.Object (org.jenkinsci.plugins.workflow.cps.CpsClosure2 tagDeployment java.lang.String). Administrators can decide whether to approve or reject this signature.```
> Revert "Tag repositories inline in their build jobs"

- vars/runCardSmokeTest.groovy
- vars/runDirectDebitSmokeTest.groovy
- vars/runProductsSmokeTest.groovy
- vars/runSmokeTest.groovy
We never call run*SmokeTest with any arguments, so remove them and hardcode the
values instead.
> Hardcode arguments to runSmokeTest

- vars/runSmokeTest.groovy
The defaults for this job are fine, we don't need to pass in these extra
parameters.
> Remove extra parameters from run-smoke-test call

- vars/tagDeployment.groovy
Only the first parameter is ever used. Remove the other two & hardcode them.
See https://github.com/search?p=1&q=org%3Aalphagov+tagdeployment&type=Code for
proof.
> Remove unused parameters from tagDeployment

- vars/runPactProviderTests.groovy
The default CONSUMER value is blank which will mean by default all tests will be run at
the provider (see
https://github.com/alphagov/pay-connector/blob/master/src/test/java/uk/gov/pay/connector/pact/ContractTestSuite.java#L29-L31)
> PP-5670: Add CONSUMER property to the maven run

- resources/cypress/cypress.yml
Use new mountebank docker image where the command specifies the `--debug` option. This allows us to verify that stubs are called.
> PP-6008 Use new mountebank docker image

- vars/gitBranchName.groovy
Previous method did not work on master. This one does
> BAU Improve branchname method

- vars/gitBranchName.groovy
Reverts alphagov/pay-jenkins-library#110 because it’s breaking all our builds!
> Revert "BAU Improve branchname method"

- .gitignore
- vars/runDirectDebitSmokeTest.groovy
Description:
- Since no Jenkins pipeline is now calling the runDirectDebit library function it is unused and so can be safely deleted
> PP-6763 - Remove direct debit Jenkins library function

- .secrets.baseline
- LICENCE
- README.md
Following the [GDS Way guidelines for Licence files](https://gds-way.cloudapps.digital/manuals/licensing.html#licensing).
This repo was also missing a secrets baseline file.
> PP-7250 Add licence file

- resources/cypress/cypress.yml
- vars/cypress.groovy
Reference `cypress/*` docker image when composing Cypress
containers. Remove reference to custom govuk pay managed image.
Use the `cypress/included` image which includes system dependencies
required to run Cypress along with Cypress itself.
Allow `CYPRESS_VERSION` to be overriden by the Jenkins environment, this 
should let each build file use its own version of Cypress if required.
> BAU Use standard Cypress image in build process

- resources/cypress/cypress.yml
Jenkins logs are difficult to read during stages that require Cypress as the colour codes are printed literally. 
By setting `NO_COLOR` to 1 this should prevent Cypress trying to colourise the logging output.
> BAU Prevent Cypress from polluting Jenkins logs

- vars/buildMultistageAppWithMetrics.groovy
This was previously contained in Dockerfile, but makes
things more flexible if tests are invoked by external
call, in case e.g. of need to build without tests
> PP-9153 Add run test command to multistage app build

- vars/buildMultistageAppWithMetrics.groovy
Follow-up to https://github.com/alphagov/pay-frontend/pull/2692 
As we are no longer running `npm snyk protect` in the Dockerfile build it makes sense to run it instead at this point in the Jenkins build against the built image.
> PP-9153: run snyk protect in pipeline
